### PR TITLE
feat: allow passing esbuild transform options

### PR DESCRIPTION
**Pull request by uuau99999**
This pr is related to issue: #39 
add esbuildOptions as prop to createLoader thus can make jsLoader using custom esbuild options while doing esbuild transform:
image

### CODE REVIEW

**Comment by uuau99999** [comment]
Yup, named as esbuild is better. Updated.

**Comment by uuau99999** [comment]
@pi0 Maybe look at this? Thanks.

**Comment by trim21** [comment]
is this new option expected to be use in js mkdist api directly?

**Comment by uuau99999** [comment]
> No new cli flag for it, is this new option expected to be use in js mkdist api directly?

Yes.  Cause esbuild options is an object and may not be suitable to pass in as cli option.
In fact, I make this pr not just to provide esbuild options to mkdist. I found unjs/unbuild is using mkdist and doesn't provide options to customize esbuild option: 

image

When using unbuild as library bundler, it is useful to allow setting esbuild option.

**Review by pi0 — APPROVED** [review]
Thanks 💯

**Pull request merged**
